### ISSUE TITLE
如果根视图是tabview，不能返回到root，请问该如何解决呢

### ISSUE THREAD

**Issue by tc976562936** [Whiffer/SwiftUI-PopToRootExample#4]
struct ContentView: View {
    @State private var isActive : Bool = false
    var body: some View {
        NavigationView {
            TabView {
                SwiftUIView1()
                    .tabItem {
                        Label("Menu", systemImage: "list.dash")
                    }
                
                SwiftUIView2()
                    .tabItem {
                        Label("Order", systemImage: "square.and.pencil")
                    }
            }
        }
        .navigationViewStyle(StackNavigationViewStyle())
        .environment(\.rootPresentationMode, self.$isActive)
    }
}
如果根视图是tabview，不能返回到root，请问该如何解决呢

**Comment by Whiffer** [comment]
Your NavigationView() seems to be misplaced. Take a look at [https://stackoverflow.com/questions/67237313/navigationview-inside-a-tabview-swift-ui](https://stackoverflow.com/questions/67237313/navigationview-inside-a-tabview-swift-ui)
